linters:
  enable:
    - asciicheck
    - bodyclose
    - wsl
    - errchkjson
    - errorlint
    - gochecknoinits
    - goimports
    - govet
    - misspell
    - nonamedreturns
    - prealloc
    - revive
    - tenv
    - whitespace
    - exportloopref

